// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbuddpspfxufhftkcaww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndidWRkcHNwZnh1ZmhmdGtjYXd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0Mzk3NzIsImV4cCI6MjA2NjAxNTc3Mn0.TZwhCDxB-mtv9OTyVZRyzYFMNFsRUd_hNGdODMWSt10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);